### ISSUE TITLE
Wiki contribution: suite of links for How-It-Works#key-technologies

### ISSUE THREAD

**Issue by rektide** [lmco/streamflow#20]
In rektide/streamflow-wiki@e3951ee6 I took the liberty of going through the POM for Streamflow and extracted project names and links that should serve as a viable start to the presently blank section of the wiki, https://github.com/lmco/streamflow/wiki/How-It-Works#key-technologies . Please consider merging the references I'm providing into your wiki.

Your wiki is very well skeletoned out, and I look forward to seeing it fleshed out from there; I'm expecting a ton of great, interesting content.

I've also filed isaacs/github#333 in hopes that maybe someday there'll be a better process for contributing to wikis than this weird filing an issue & linking you the commit to merge yourself.

**Comment by juliencruz** [comment]
Thanks for adding this to the Wiki documentation.  We are in the process of migrating much of our documentation from an internal wiki site so expect to see a ton of updates for the rest of the skeleton in the next couple of days.   I do agree with a potential improvement for the wiki contribution as it would simply things greatly.

**Comment by juliencruz** [comment]
Merged changes into master
