### ISSUE TITLE
Storm 0.9.3and Kafka 0.8.1.1

### ISSUE THREAD

**Issue by jloveland** [lmco/streamflow#24]
We should upgrade to the latest [Storm 0.9.3 version](https://storm.apache.org/2014/11/25/storm093-released.html)

Additionally, this would lend itself to upgrading to [Kafka 0.8.1.1](https://github.com/apache/storm/blob/v0.9.3/external/storm-kafka/pom.xml#L98)

**Comment by juliencruz** [comment]
Agreed, we can do some testing to verify the upgrades to Storm 0.9.3 and Kafka 0.8.1.1.

**Comment by juliencruz** [comment]
Compatibility with Storm 0.9.3 has been validated locally and on the cluster.  Kafka modifications still require verification and validation.

**Comment by juliencruz** [comment]
Closing due to overlap with #37
